travis:
  secure:
    BINSTAR_TOKEN: G1wk9aoSChnGhdHfaDCXSZYfgrfpTb6BezRgOu0KA5tx1pyNXPgyNNcfPZ4b+zSHftu1hoZsxQgO77jII6Yj2GQ9Cj92JyEyTrsP2EQaDSeGjQtuPkX0dgodxtldwIfV0gzIz7iTMnNG5c4i4UdDD57Y5evOI54AAOco9fL0mtax6rQ8v2esMwWGWil9fYsdIrxjjb+xLF1mLOTzWoxmWzvVeZIAkgdxmCxOjwgT4c9q4mf9dYGpMVionkXRhNd3DTlmHR//Jb0FXHos7QEo76f9pYKW6C3dE5ZR7u1v9OZeTbhf1kYPFs9NJ6TebxjlslXBjxwfTxOfiNc5gPAVZaUyWvmV5MZhtUp7Uewm9+2ztKcUYKKgpMr2FF3fYLcrlhIAG+QLYC/6AwqDRAOnhw4AV5omRJ/sji6oI61jT8WfPb6S7f8IbzvBd032syg6THJNvrWblfq0PZDaQ7UPxKi4V8IZpN8sAUMhPxm/y0fXB3LFTBBFMzlPPKMiVDUc20Zz7xrDFJ0t+pK3/oamkzm6AYT7bTawLUkBFc95AVsiQNjCdd4AygxFHt8cRTOYQ2IMTRqFFaD4EDabwy5Zcz0wT5nuiiFQ7NvAJTnBcUZ5MQQwMkXpl9AHqOAPn5H/YRU7UvQBeAhlkai9BCZYe6xReS/mUPzPPLKk+0Gdkmg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
