travis:
  secure:
    BINSTAR_TOKEN: wkLJ4b5ctSb3fXMMcouqFGaDSH7FYoB5ruBP2eALBKoe8IL91Md+CUBufRVSfE5qqH8bWpUhhHj7DlxkLsUEJpg+b5Kpg0AmqlRWzrjKHjcRoSwe2xXyYBWWlFQkekwfaaoQSBHZFRbDJzEtkkkqsIVErYVpaok4ejt/h4nfDFgI1r61G0KTvr/E9FQ82pEc1EKusUVp6vt1rTAQZkOFVNbapA3wtUTYJ2KFORZTL5rjo+o2eBwd7CkZets7QNeroD6Hq9hD5vto4V59Kn9ecPh8KTTnLJovdF9he6VRvGaur7JbeNYDrfWt+jhvEl4gEz/CGXvKA2bJoskt+DWSHJlLWtVKldHndze/bmRrl/8OidlkQSzR5Zpd4DpOhbEIROGty9A0OUdjvQ0REWkjp+Dzpk4hlLXF71i48b7SzLEgJOiZ1GB/llzAFPWQZjmpQVpYcTK9T0UebsonKtDaeT+vX8uQwvcQZvaLftv9gHx8FNADB46Uh8gfJxdtCvOWXr4qi8UcUIfY5lze+E84fIdtmqjlcGJEAnbrNOYK6aq3/hUXtVHTlRlM+AGVHUTHlBNUUMXbBmy2VRF0NYHDfJXk01ZtBbeeeuvZq1GMVWdjXxYy5DoCUTCfCfDcHa7ARRhu2/jBO4SAYmGjj0/uZoLW9jtiC5lvbodzRJ4RPko=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
